# Generated by Django 5.1.4 on 2025-01-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
